# Generated by Django 4.2.2 on 2025-07-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "ITEM",
                "verbose_name_plural": "ITEMS",
            },
        ),
    ]
